trigger:
  - main

resources:
  - repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerRegistryServiceConnection: '8b99373d-09da-42e0-bc54-293a8e22cdcb'
  MAVEN_OPTS: '-Xmx3072m'

stages:
  - stage: Build
    displayName: Build and Push Image
    jobs:
      - job: Build
        displayName: Build and Push
        pool:
          vmImage: ubuntu-latest
        steps:
          # Install Java 21
          - task: JavaToolInstaller@0
            inputs:
              versionSpec: '21'
              jdkArchitectureOption: 'x64'
              jdkSourceOption: 'PreInstalled'

          # Download and Install Maven
          - script: |
              # Define Maven version and installation directory
              MAVEN_VERSION=3.8.6
              MAVEN_HOME=/usr/local/maven

              # Download Maven
              wget https://apache.osuosl.org/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz

              # Extract and install Maven
              tar -xzf apache-maven-$MAVEN_VERSION-bin.tar.gz
              sudo mv apache-maven-$MAVEN_VERSION $MAVEN_HOME
              
              # Set Maven environment variables
              echo 'M2_HOME=$MAVEN_HOME' | sudo tee -a /etc/environment
              echo 'PATH=$M2_HOME/bin:$PATH' | sudo tee -a /etc/environment
              source /etc/environment
              
              # Verify Maven installation
              mvn -version
            displayName: 'Install Maven'

          # Cache Maven dependencies
          - task: Cache@2
            inputs:
              key: 'v2 | maven | "$(Agent.OS)" | **/pom.xml'
              restoreKeys: |
                v2 | maven | "$(Agent.OS)"
                v2 | maven
              path: $(Pipeline.Workspace)/.m2/repository
            displayName: Cache Maven local repo

          # Maven build step
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '$(MAVEN_OPTS)'  # Use Maven options here
              goals: 'clean install'
              options: '-B'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '21'

          # Docker build and push step
          - task: Docker@2
            displayName: Build and push image to container registry
            inputs:
              command: buildAndPush
              repository: 'premkumar'
              dockerfile: '$(Build.SourcesDirectory)/build/Dockerfile'
              containerRegistry: '$(dockerRegistryServiceConnection)'
              tags: |
                latest
                $(tag)
