trigger:
  - main

resources:
  - repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build and Push Images
    jobs:
      - job: Build
        displayName: Build and Push
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m $(MAVEN_OPTS)'
              goals: 'clean install'
              options: '-B'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.22'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: true
              effectivePomSkip: false
              sonarQubeRunAnalysis: false


          # Docker build step for the linker image
          - task: Docker@2
            displayName: Build Linker Image
            inputs:
              command: build
              dockerfile: '$(Build.SourcesDirectory)/build/LinkerDockerfile'
              tags: |
                linker-$(tag)
              platform: 'linux/amd64'

          # Login to Azure Container Registry
          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: '8b99373d-09da-42e0-bc54-293a8e22cdcb'



          # Push the linker image to ACR
          - task: Docker@2
            displayName: Push Linker Image to ACR
            inputs:
              command: push
              tags: |
                linker-$(tag)
              repository: 'premkumar.azurecr.io/linker'
