trigger:
  - main

resources:
  - repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build and Push Image
    jobs:
      - job: Build
        displayName: Build and Push
        pool:
          vmImage: ubuntu-latest
        steps:
          # Step to perform mvn clean install
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m $(MAVEN_OPTS)'
              goals: 'clean install'
              options: '-B'  # Optional, adds batch mode to reduce log output
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.22'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: true
              effectivePomSkip: false
              sonarQubeRunAnalysis: false

          # Docker build step
          - task: Docker@2
            displayName: Build an image
            inputs:
              command: build
              dockerfile: '$(Build.SourcesDirectory)/build/Dockerfile'
              tags: |
                $(tag)
              platform: 'linux/amd64'

          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: '8b99373d-09da-42e0-bc54-293a8e22cdcb'

          - task: Docker@2
            displayName: Push image to ACR
            inputs:
              command: push
              tags: |
                $(tag)
              repository: 'premkumar.azurecr.io/myapp'
