trigger:
  - main

resources:
  - repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerRegistryServiceConnection: '8b99373d-09da-42e0-bc54-293a8e22cdcb'

stages:
  - stage: Build
    displayName: Build and Push Image
    jobs:
      - job: Build
        displayName: Build and Push
        pool:
          vmImage: ubuntu-latest
        steps:
          # Install Java 21
          - task: JavaToolInstaller@0
            inputs:
              versionSpec: '21'
              jdkArchitectureOption: 'x64'
              jdkSourceOption: 'PreInstalled'

          # Check Java Version (for verification)
          - script: java -version
            displayName: 'Check Java Version'

          # Cache Maven dependencies
          - task: Cache@2
            inputs:
              key: 'v2 | maven | "$(Agent.OS)" | **/pom.xml'
              restoreKeys: |
                v2 | maven | "$(Agent.OS)"
                v2 | maven
              path: $(Pipeline.Workspace)/.m2/repository
            displayName: Cache Maven local repo

          # Maven build step
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m $(MAVEN_OPTS)'
              goals: 'clean install'
              options: '-B'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '21'

          # Docker build and push step
          - task: Docker@2
            displayName: Build and push image to container registry
            inputs:
              command: buildAndPush
              repository: 'premkumar'
              dockerfile: '$(Build.SourcesDirectory)/build/Dockerfile'
              containerRegistry: '$(dockerRegistryServiceConnection)'
              tags: |
                latest
                $(tag)
